### ISSUE TITLE
Incompatible Jackson version: 2.8.3

### ISSUE THREAD

**Issue by asos-srinija** [Azure/azure-documentdb-spark#21]
Hi ,
I am using your recent version and I am facing version incompatibility issue during runtime.
below is the list of my included dependencies.
Can you look into this and help me to sort this out.
scalaVersion := "2.11.8"
val sparkVersion = "2.1.0"
libraryDependencies += "com.eed3si9n" % "sbt-assembly_2.8.1" % "sbt0.10.1_0.6"
libraryDependencies += "org.apache.spark" % "spark-core_2.11" % sparkVersion % "provided"
libraryDependencies += "org.apache.spark" % "spark-sql_2.11" % sparkVersion % "provided"
libraryDependencies += "org.apache.spark" % "spark-mllib_2.11" % sparkVersion % "provided"
libraryDependencies += "org.apache.spark" % "spark-hive_2.11" % sparkVersion % "provided"
libraryDependencies += "com.microsoft.azure" % "azure-documentdb-spark" % "0.0.2"
libraryDependencies += "org.mongodb.scala" % "mongo-scala-driver_2.11" % "1.0.1"

**Comment by dennyglee** [comment]
Hi @asos-srinija - the Jackson version 2.8.3 is coming from our Java SDK while Spark itself uses Jackson version 2.6.5.  Saying this, if you build `azure-document-spark` separately and include it via the --jars then there shouldn't be any conflicts.  By any chance will that work?

**Comment by asos-srinija** [comment]
Hi dennyglee, I have generated fat jar and included it into my scala project. Does that make any difference ?

**Comment by dennyglee** [comment]
It does because by creating the fat jar, the DocumentDB Java SDK Jackson dependency conflicts with the Spark Jackson dependency.  To minimize / avoid the conflicts, best to keep them separate.

**Comment by valencik** [comment]
Hello!
We experience a very similar issue with the regular Azure DocumentDB (`com.microsoft.azure` `azure-documentdb` `1.9.3`) library and Spark 2.0.2.
We overcame this by including a dependency override in the build.sbt:
`dependencyOverrides ++= Set("com.fasterxml.jackson.core" % "jackson-databind" % "2.6.1")`

**Comment by asos-srinija** [comment]
@valencik  Thanks for your suggestion. It fixed my issue.
